"""
15 会话生命周期时间线蓝图配置模块。
定义了包含 8 种模版（T2-4, T2-2, T2-1, T1-2, T2-5, X-1, T2-3, T1-1）的完整会话序列结构。
"""

def get_15_session_blueprints(
    main_mt: dict,
    sub_01: dict,
    sub_02: dict,
    dist_01: dict,
    dist_02: dict,
    evt_01: dict,
    decl_mode: str,
    storyline_trigger_type: str,
    main_env_desc: str,
    main_trigger_desc: str,
) -> list[dict]:
    """
    生成 15 会话的标准蓝图配置列表。
    """
    return [
        # 01: Main Evidence (T2-4 首次建联证据)
        {
            "idx": 1,
            "ref_time": "2026年10月07日13时45分",
            "template_id": "T2-4",
            "role": "evidence_session",
            "source": main_mt,
            "type": "main",
            "start": "2026年10月07日14时00分",
            "end": "2026年10月07日16时00分",
            "dur": "120min",
            "env": main_env_desc,
            "action": "declare_explicit_rule" if decl_mode == "explicit_declaration" else "single_task_implicit_behavior",
            "declaration_mode": decl_mode,
            "storyline_trigger_type": storyline_trigger_type,
            "trigger_condition": main_trigger_desc,
        },
        # 02: Sub 1 Evidence (T2-2 歧义消解)
        {
            "idx": 2,
            "ref_time": "2026年10月11日18时30分",
            "template_id": "T2-2",
            "role": "evidence_session",
            "source": sub_01,
            "type": "sub_01",
            "start": "2026年10月11日18时45分",
            "end": "2026年10月11日19时45分",
            "dur": "60min",
            "env": "大巴跨城转场高速公路",
            "action": "disambiguate_sub_storyline_1",
            "declaration_mode": "implicit_induction",
            "storyline_trigger_type": "location_environment",
            "trigger_condition": "大巴转场弱网环境",
        },
        # 03: Main Reinforcement (T2-1 主线强化/固化契机)
        {
            "idx": 3,
            "ref_time": "2026年10月14日13时50分",
            "template_id": "T2-1",
            "role": "reinforcement_session",
            "source": main_mt,
            "type": "main",
            "start": "2026年10月14日14时00分",
            "end": "2026年10月14日16时00分",
            "dur": "120min",
            "env": main_env_desc,
            "action": "reinforce_explicit_memory" if decl_mode == "explicit_declaration" else "crystallize_implicit_memory",
            "declaration_mode": decl_mode,
            "storyline_trigger_type": storyline_trigger_type,
            "trigger_condition": main_trigger_desc,
        },
        # 04: Sub 2 Evidence (T2-1 支线2建联)
        {
            "idx": 4,
            "ref_time": "2026年10月15日20时00分",
            "template_id": "T2-1",
            "role": "evidence_session",
            "source": sub_02,
            "type": "sub_02",
            "start": "2026年10月15日20时15分",
            "end": "2026年10月15日21时45分",
            "dur": "90min",
            "env": "驻地酒店休息区",
            "action": "establish_sub_storyline_2",
            "declaration_mode": "implicit_induction",
            "storyline_trigger_type": "location_environment",
            "trigger_condition": "驻地酒店休息区",
        },
        # 05: Distractor 1 (T1-2 纯域外拒绝，如宽带光纤报修)
        {
            "idx": 5,
            "ref_time": "2026年10月18日10时00分",
            "template_id": "T1-2",
            "role": "distractor_session",
            "source": dist_01,
            "type": "distractor_ood",
            "start": "2026年10月18日10时00分",
            "end": "2026年10月18日10时30分",
            "dur": "30min",
            "env": "酒店临时办公区网络故障",
            "action": "reject_out_of_domain",
            "ood_goal": "宽带光纤装维报修",
        },
        # 06: Sub 1 Reinforcement (T2-1 支线1复用/强化)
        {
            "idx": 6,
            "ref_time": "2026年10月21日18时40分",
            "template_id": "T2-1",
            "role": "reinforcement_session",
            "source": sub_01,
            "type": "sub_01",
            "start": "2026年10月21日19时00分",
            "end": "2026年10月21日20时00分",
            "dur": "60min",
            "env": "大巴转场途中",
            "action": "reinforce_sub_storyline_1",
        },
        # 07: Main Reuse (T2-5 变更延长时长至 180min)
        {
            "idx": 7,
            "ref_time": "2026年10月24日13时45分",
            "template_id": "T2-5",
            "role": "reuse_session",
            "source": main_mt,
            "type": "main",
            "start": "2026年10月24日14时00分",
            "end": "2026年10月24日17时00分",
            "dur": "180min",
            "env": main_env_desc,
            "action": "extend_duration_amend",
            "storyline_trigger_type": storyline_trigger_type,
            "trigger_condition": main_trigger_desc,
        },
        # 08: Main Reinforcement (T2-1 主线常规强化)
        {
            "idx": 8,
            "ref_time": "2026年10月28日13时50分",
            "template_id": "T2-1",
            "role": "reinforcement_session",
            "source": main_mt,
            "type": "main",
            "start": "2026年10月28日14时00分",
            "end": "2026年10月28日16时00分",
            "dur": "120min",
            "env": main_env_desc,
            "action": "reinforce_main_memory",
            "storyline_trigger_type": storyline_trigger_type,
            "trigger_condition": main_trigger_desc,
        },
        # 09: Sub 2 Reinforcement (T2-1 支线2强化)
        {
            "idx": 9,
            "ref_time": "2026年10月29日20时10分",
            "template_id": "T2-1",
            "role": "reinforcement_session",
            "source": sub_02,
            "type": "sub_02",
            "start": "2026年10月29日20时30分",
            "end": "2026年10月29日22时00分",
            "dur": "90min",
            "env": "驻地复盘业务",
            "action": "reinforce_sub_storyline_2",
        },
        # 10: Distractor 2 (X-1 混合诉求一办一拒)
        {
            "idx": 10,
            "ref_time": "2026年11月01日12时30分",
            "template_id": "X-1",
            "role": "distractor_session",
            "source": dist_02,
            "type": "distractor_mixed",
            "start": "2026年11月01日12时30分",
            "end": "2026年11月01日13时30分",
            "dur": "60min",
            "env": "周末午休个人时间",
            "action": "mixed_in_out_domain",
            "ood_goal": "手机话费充值与账单查询",
        },
        # 11: Event Correction (T2-3 恶劣天气临时纠正覆盖)
        {
            "idx": 11,
            "ref_time": "2026年11月04日13时40分",
            "template_id": "T2-3",
            "role": "correction_session",
            "source": main_mt,
            "type": "event_override",
            "start": "2026年11月04日14时00分",
            "end": "2026年11月04日16时00分",
            "dur": "120min",
            "env": evt_01.get("scene_description", "恶劣环境临时保障"),
            "action": "override_temporary_preference",
            "override": evt_01.get("preference_override", {}),
        },
        # 12: Event Reuse (T2-1 临时高规格复用)
        {
            "idx": 12,
            "ref_time": "2026年11月07日13时45分",
            "template_id": "T2-1",
            "role": "reuse_session",
            "source": main_mt,
            "type": "event_reuse",
            "start": "2026年11月07日14时00分",
            "end": "2026年11月07日16时00分",
            "dur": "120min",
            "env": "特殊事件集结区",
            "action": "reuse_temporary_preference",
            "override": evt_01.get("preference_override", {}),
        },
        # 13: Sub 1 Reuse (T2-1 支线隔离验证)
        {
            "idx": 13,
            "ref_time": "2026年11月11日18时35分",
            "template_id": "T2-1",
            "role": "reuse_session",
            "source": sub_01,
            "type": "sub_01",
            "start": "2026年11月11日19时00分",
            "end": "2026年11月11日20时00分",
            "dur": "60min",
            "env": "转场大巴途中",
            "action": "sub_memory_unaffected",
        },
        # 14: Distractor 1 (T1-1 单轮单次业务)
        {
            "idx": 14,
            "ref_time": "2026年11月15日10时00分",
            "template_id": "T1-1",
            "role": "distractor_session",
            "source": dist_01,
            "type": "distractor",
            "start": "2026年11月15日10时00分",
            "end": "2026年11月15日10时30分",
            "dur": "30min",
            "env": "阶段工作总结会",
            "action": "distractor_no_memory",
        },
        # 15: Event Expiry & Main Recovery (T2-1 临时失效主线恢复)
        {
            "idx": 15,
            "ref_time": "2026年11月18日13时45分",
            "template_id": "T2-1",
            "role": "reuse_session",
            "source": main_mt,
            "type": "main_recovery",
            "start": "2026年11月18日14时00分",
            "end": "2026年11月18日16时00分",
            "dur": "120min",
            "env": main_env_desc,
            "action": "recover_long_term_rule",
            "storyline_trigger_type": storyline_trigger_type,
            "trigger_condition": main_trigger_desc,
        },
    ]
